#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias goTrivit='cd ~/Dropbox/app/trivit'
alias gotrivit='cd ~/Dropbox/app/trivit'
alias goBalloonIncWeb='cd ~/Dropbox/app/balloonincweb'
alias goballoonincweb='cd ~/Dropbox/app/balloonincweb'
alias goWinkln='cd ~/Dropbox/app/Winkln.be/winkln.be-ios'
alias gowinkln='cd ~/Dropbox/app/Winkln.be/winkln.be-ios'

alias goT='cd ~/Dropbox/app/trivit'
alias goW='cd ~/Dropbox/app/Winkln.be/winkln.be-ios'

# Lifx aliases
alias loff='lifx light power off'
alias lon='lifx light power on'
alias l20='lifx light color -B 13107'
alias l40='lifx light color -B 26214'
alias l60='lifx light color -B 39321'
alias l80='lifx light color -B 52428'
alias l100='lifx light color -B 65535'

function lazygit() {
    git add .
    git commit -a -m "$1"
    git push
}

# filtered top, pass process name as parameter
topd(){
    top -p `pgrep $1 | tr "\\n" "," | sed 's/,$//'`
}
